version: "3"
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: always
  react:
    image: "ghcr.io/wooseongshin/client:latest"
    restart: always
  api:
    image: "ghcr.io/wooseongshin/api:latest"
    restart: always
  socket:
    image: "ghcr.io/wooseongshin/socket:latest"
    restart: always
