version: "3"
services:
  react:
    image: "ghcr.io/wooseongshin/client:latest"
    restart: always
    build:
        dockerfile: Dockerfile
        context: ../client

  api:
    image: "ghcr.io/wooseongshin/api:latest"
    restart: always
    build:
      dockerfile: apiDockerfile
      context: ../server

  socket:
    image: "ghcr.io/wooseongshin/socket:latest"
    restart: always
    build:
      dockerfile: socketDockerfile
      context: ../server

