name: deploy
on:
  push:
    branches: ["dev"]

jobs:
  ci-cd:
    name: ci-cd 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16

    - name: Build React App
      working-directory: ./client
      run: |
        npm i
        npm run build 
        
    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

    - name: Copy Docker Compose into the Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        port: 22
        source: "docker-compose.yml"
        target: "/kittyMark"
        
    - name: Docker-compose build and push
      uses: pennsignals/publish_docker-compose@v0.1.0
      with:
        docker_compose: docker-compose-build.yml
        repo_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

    - name: Run Docker Compose on the Server
      uses: appleboy/ssh-action@master
      env: 
        TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        envs: TOKEN
        script: |
          docker login https://ghcr.io -u wooseongshin -p "$TOKEN"
          cd kittyMark
          docker compose pull
          docker compose up -d
    
        
